name: Run Tests

on: [push, pull_request]

jobs:
    test-styles:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: cachix/install-nix-action@v27
            - run: nix-shell --pure -I nixpkgs=channel:nixos-26.05 --run "make test-styles"
    # test-colors:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - uses: actions/checkout@v4
    #         - run: make test-colors
